name: Deploy to Heroku

on:
  push:
    branches:
      - develop  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8
        run: |
          pip install flake8
          flake8 || true  # Continue on error to report all issues
        # Archive Flake8 report as artifact
        - name: Archive Flake8 report
          if: always()  # Always archive, even if previous steps fail
          uses: actions/upload-artifact@v2
          with:
            name: flake8-report
            path: flake8-report.txt

      - name: Run tests
        run: |
          python manage.py test
        # Archive test reports as artifacts
        - name: Archive test reports
          if: always()  # Always archive, even if previous steps fail
          uses: actions/upload-artifact@v2
          with:
            name: test-reports
            path: |
              ./logs/
              ./coverage/

      - name: Set up Heroku CLI
        run: |
          wget -qO- https://toolbelt.heroku.com/install.sh | sh
          heroku --version  # Verify Heroku CLI installation
